export const resources = [
  { key: 'AshwinderEggs', value: 'Ashwinder Eggs' },
  { key: 'Diricawl_Byproduct', value: 'Diricawl Feather' },
  { key: 'Dittany_Byproduct', value: 'Dittany Leaves' },
  { key: 'Dugbog_Pellet', value: 'Dugbog Tongue' },
  { key: 'Fertiliser', value: 'Fertiliser' },
  { key: 'Fluxweed_Byproduct', value: 'Fluxweed Stem' },
  { key: 'Fwooper_Byproduct', value: 'Fwooper Feather' },
  { key: 'Graphorn_Byproduct', value: 'Graphorn Horn' },
  { key: 'Hippogriff_Byproduct', value: 'Hippogriff Feather' },
  { key: 'HorklumpJuice', value: 'Horklump Juice' },
  { key: 'Jobberknoll_Byproduct', value: 'Jobberknoll Feather' },
  { key: 'Kneazle_Byproduct', value: 'Kneazle Fur' },
  { key: 'Knotgrass_Byproduct', value: 'Knotgrass Sprig' },
  { key: 'LacewingFlies', value: 'Lacewing Flies' },
  { key: 'LeechJuice', value: 'Leech Juice' },
  { key: 'LeapingToadstool_Byproduct', value: 'Leaping Toadstool Caps' },
  { key: 'Mallowsweet_Byproduct', value: 'Mallowsweet Leaves' },
  { key: 'Mooncalf_Byproduct', value: 'Mooncalf Fur' },
  { key: 'Wolf_Byproduct', value: 'Mongrel Fur' },
  { key: 'Moonstone', value: 'Moonstone' },
  { key: 'Niffler_Byproduct', value: 'Niffler Fur' },
  { key: 'Puffskein_Byproduct', value: 'Puffskein Fur' },
  { key: 'Shrivelfig_Byproduct', value: 'Shrivelfig Fruit' },
  { key: 'Spider_Fang', value: 'Spider Fang' },
  { key: 'StenchOfTheDead', value: 'Stench Of The Dead' },
  { key: 'Thestral_Byproduct', value: 'Thestral Hair' },
  { key: 'Toad_Byproduct', value: 'Toad Warts' },
  { key: 'TrollMucus', value: 'Troll Bogeys' },
  { key: 'Unicorn_Byproduct', value: 'Unicorn Hair' },
] as const

export const sanctuary = [
  { key: 'ChompingCabbage_Byproduct', value: 'Chinese Chomping Cabbage' },
  { key: 'Edurus', value: 'Edurus Potion' },
  { key: 'AMFillPotion', value: 'Focus Potion' },
  { key: 'InvisibilityPotion', value: 'Invisibility Potion' },
  { key: 'Mandrake_Byproduct', value: 'Mandrake' },
  { key: 'Maxima', value: 'Maxima Potion' },
  { key: 'AutoDamagePotion', value: 'Thunderbrew' },
  { key: 'VenomousTentacula_Byproduct', value: 'Venomous Tentacula' },
] as const

export const health = [
  { key: 'WoundCleaning', value: 'Wiggenweld Potion' },
] as const

export const talents = [
  { key: 'Talent_Spell_Accio', value: 'Accio Mastery' },
  { key: 'Talent_Core_OppugnoQuick', value: 'Ancient Magic Throw Expertise' },
  { key: 'Talent_Curse_AvadaKedavra', value: 'Avada Kedavra Mastery' },
  { key: 'Talent_Core_JinxAM', value: 'Basic Cast Airborne Absorption' },
  { key: 'Talent_Core_JinxCooldown', value: 'Basic Cast Mastery' },
  { key: 'Talent_Spell_Bombarda', value: 'Bombarda Mastery' },
  { key: 'Talent_Spell_Confringo', value: 'Confringo Mastery' },
  { key: 'Talent_Curse_Crucio', value: 'Crucio Mastery' },
  { key: 'Talent_Curse_CurseHealth', value: 'Curse Sapper' },
  { key: 'Talent_Spell_Depulso', value: 'Depulso Mastery' },
  { key: 'Talent_Spell_Descendo', value: 'Descendo Mastery' },
  { key: 'Talent_Spell_Diffindo', value: 'Diffindo Mastery' },
  { key: 'Talent_Spell_Expelliarmus', value: 'Disarming Curse' },
  { key: 'Talent_Sanc_EdurusPotion', value: 'Edurus Potion Potency' },
  { key: 'Talent_Curse_CurseLong', value: 'Enduring Cure' },
  { key: 'Talent_Core_DodgeAM', value: 'Evasion Absorption' },
  { key: 'Talent_Sanc_Cabbage', value: 'Fertiliser' },
  { key: 'Talent_Sanc_AMPotion', value: 'Focus Potion Potency' },
  { key: 'Talent_Spell_Glacius', value: 'Glacius Mastery' },
  { key: 'Talent_Sanc_Mandrake', value: 'Headache' },
  { key: 'INF_Swift', value: 'Human Demiguise' },
  { key: 'Talent_Curse_Imperio', value: 'Imperio Mastery' },
  { key: 'Talent_Spell_Incendio', value: 'Incendio Mastery' },
  { key: 'Talent_Sanc_InvisibilityPotion', value: 'Invisibility Potion Potency' },
  { key: 'Talent_Spell_Flippendo', value: 'Knockback Curse' },
  { key: 'Talent_Spell_Levioso', value: 'Levioso Mastery' },
  { key: 'Talent_Sanc_MaximaPotion', value: 'Maxima Potion Potency' },
  { key: 'Talent_Sanc_Venomous', value: 'Noxious' },
  { key: 'Talent_Infil_PetrificusTotalus', value: 'Petrificus Totalus Mastery' },
  { key: 'SKILL_FocusGain', value: 'Protego Absorption' },
  { key: 'DUEL_Deflect1', value: 'Protego Expertise' },
  { key: 'Talent_Core_ProtegoBlast', value: 'Protego Mastery' },
  { key: 'Talent_Core_RevelioUpgrade', value: 'Revelio Mastery' },
  { key: 'Talent_Infil_Evasion1', value: 'Sense of Secrecy I' },
  { key: 'Talent_Infil_Evasion2', value: 'Sense of Secrecy II' },
  { key: 'Talent_Spell_Arresto', value: 'Slowing Curse' },
  { key: 'GEN_SpellLoadouts_1', value: 'Spell Knowledge I' },
  { key: 'GEN_SpellLoadouts_2', value: 'Spell Knowledge II' },
  { key: 'GEN_SpellLoadouts_3', value: 'Spell Knowledge III' },
  { key: 'DAC_CurseReflect1', value: 'Stunning Curse' },
  { key: 'Talent_Curse_CurseStupefy', value: 'Stunning Curse' },
  { key: 'Talent_Core_StupefyAOE', value: 'Stupefy Expertise' },
  { key: 'Talent_Core_StupefyStun', value: 'Stupefy Mastery' },
  { key: 'Talent_Core_DodgeFast', value: 'Swift' },
  { key: 'Talent_Sanc_AutoDamagePotion', value: 'Thunderbrew Potency' },
  { key: 'Talent_Spell_Transformation', value: 'Transformation Mastery' },
  { key: 'LOW_WoundCleaningUpgrade1', value: 'Wiggenweld Potency I' },
  { key: 'LOW_WoundCleaningUpgrade2', value: 'Wiggenweld Potency II' },
] as const
